import{useEffect,useState}from'react';import{BookOpen,Search,Library,Heart,History,Sun,Moon,ChevronLeft,ScrollText,Sparkles}from'lucide-react';import{api,Work,Segment,SearchHit}from'./services/api';

type View='home'|'library'|'reader'|'search';
const seeds=[['תנ״ך','תורה, נביאים וכתובים'],['משנה','שישה סדרי משנה'],['תלמוד','בבלי וירושלמי'],['הלכה','רמב״ם, טור ושולחן ערוך'],['תפילה','סידורים, מחזורים ופיוטים'],['מדרש','מדרשי חז״ל'],['מוסר','ספרי מוסר ומחשבה'],['חסידות','ספרי חסידות']];
export default function App(){const[view,setView]=useState<View>('home');const[works,setWorks]=useState<Work[]>([]);const[selected,setSelected]=useState<Work|null>(null);const[segments,setSegments]=useState<Segment[]>([]);const[q,setQ]=useState('');const[hits,setHits]=useState<SearchHit[]>([]);const[dark,setDark]=useState(false);const[busy,setBusy]=useState(false);
useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);
async function loadLibrary(){setBusy(true);try{setWorks(await api.works());setView('library')}finally{setBusy(false)}}
async function openWork(w:Work){setBusy(true);try{setSelected(w);setSegments(await api.segments(w.id));setView('reader')}finally{setBusy(false)}}
async function runSearch(e?:React.FormEvent){e?.preventDefault();if(q.trim().length<2)return;setBusy(true);try{setHits(await api.search(q.trim()));setView('search')}finally{setBusy(false)}}
return <div className="app"><header><button className="brand" onClick={()=>setView('home')}><span className="mark">א</span><span><b>אוצר ישראל</b><small>ארון הספרים היהודי</small></span></button><nav><button onClick={()=>setView('home')}>בית</button><button onClick={loadLibrary}>ספרייה</button><button onClick={()=>{setQ('');setHits([]);setView('search')}}>חיפוש</button></nav><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button></header>
<main>{view==='home'&&<><section className="hero"><div className="kicker"><Sparkles size={16}/> כל ארון הספרים היהודי במקום אחד</div><h1>לגלות. ללמוד. להתפלל.<br/><span>אוצר ישראל.</span></h1><p>מאגר יהודי פתוח שמחבר תנ״ך, חז״ל, הלכה, תפילה, מחשבה ופרשנות למרחב לימוד אחד.</p><form className="searchbox" onSubmit={runSearch}><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="חפש פסוק, ביטוי, ספר או נושא..."/><button>חיפוש</button></form></section><section className="section"><div className="sectionHead"><div><span>הספרייה</span><h2>פתח את ארון הספרים</h2></div><button className="link" onClick={loadLibrary}>לכל הספרים <ChevronLeft/></button></div><div className="grid">{seeds.map(([t,d])=><button className="category" key={t} onClick={loadLibrary}><BookOpen/><b>{t}</b><span>{d}</span></button>)}</div></section><section className="features"><div><ScrollText/><b>מקור ורישיון לכל טקסט</b><span>כל מהדורה נשמרת עם מקור שימוש ברור.</span></div><div><Search/><b>חיפוש עברי מנורמל</b><span>חיפוש גם בטקסט מנוקד ובכתיב משתנה.</span></div><div><Library/><b>מבנה שמוכן לגדול</b><span>מתוכנן מראש לעשרות אלפי יצירות.</span></div></section></>}
{view==='library'&&<section className="page"><h1>ספריית אוצר ישראל</h1><p>כל הספרים שכבר נטענו למאגר.</p>{busy?<div className="empty">טוען…</div>:works.length===0?<div className="empty"><BookOpen/><b>הספרייה מוכנה לייבוא הראשון</b><span>לאחר חיבור מסד הנתונים והרצת היבואן יופיעו כאן הספרים.</span></div>:<div className="bookList">{works.map(w=><button key={w.id} onClick={()=>openWork(w)}><div><b>{w.title_he}</b><span>{w.category}{w.author?` · ${w.author}`:''}</span></div><ChevronLeft/></button>)}</div>}</section>}
{view==='reader'&&selected&&<section className="reader"><aside><span>{selected.category}</span><h2>{selected.title_he}</h2><button onClick={loadLibrary}>חזרה לספרייה</button></aside><article><div className="readerTop"><div><small>{selected.category}</small><h1>{selected.title_he}</h1></div><div><button className="icon"><Heart/></button><button className="icon"><History/></button></div></div>{segments.map(s=><p key={s.id}><sup>{s.ref.split(' ').slice(-1)}</sup>{s.text}</p>)}</article></section>}
{view==='search'&&<section className="page"><h1>חיפוש באוצר ישראל</h1><form className="searchbox compact" onSubmit={runSearch}><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="מה תרצה למצוא?"/><button>חיפוש</button></form>{busy?<div className="empty">מחפש…</div>:hits.length?<div className="results">{hits.map((h,i)=><button key={i} onClick={async()=>{const w=works.find(x=>x.id===h.work_id)||(await api.works()).find(x=>x.id===h.work_id);if(w)openWork(w)}}><b>{h.work_title}</b><small>{h.ref}</small><p>{h.text}</p></button>)}</div>:q?<div className="empty">לא נמצאו תוצאות.</div>:<div className="empty"><Search/><b>חיפוש בכל ארון הספרים</b><span>כתוב לפחות שתי אותיות כדי להתחיל.</span></div>}</section>}</main><footer>אוצר ישראל · גרסת יסוד 0.1.0</footer></div>}
