import{useEffect,useMemo,useState}from'react';import{BookOpen,Search,Library,Heart,History,Sun,Moon,ChevronLeft,ChevronRight,ScrollText,Sparkles,BarChart3}from'lucide-react';import{api,Work,Segment,SearchHit,Stats,SectionInfo}from'./services/api';

type View='home'|'library'|'reader'|'search';
const seeds=[['Tanakh','תנ״ך','תורה, נביאים וכתובים'],['Mishnah','משנה','שישה סדרי משנה'],['Talmud','תלמוד','בבלי וירושלמי'],['Halakhah','הלכה','רמב״ם, טור ושולחן ערוך'],['Liturgy','תפילה','סידורים, מחזורים ופיוטים'],['Midrash','מדרש','מדרשי חז״ל'],['Musar','מוסר','ספרי מוסר ומחשבה'],['Chasidut','חסידות','ספרי חסידות']];
const categoryHe=(v:string)=>Object.fromEntries(seeds.map(x=>[x[0],x[1]]))[v]||v;
export default function App(){const[view,setView]=useState<View>('home');const[works,setWorks]=useState<Work[]>([]);const[selected,setSelected]=useState<Work|null>(null);const[segments,setSegments]=useState<Segment[]>([]);const[sections,setSections]=useState<SectionInfo[]>([]);const[currentSection,setCurrentSection]=useState<number|undefined>();const[q,setQ]=useState('');const[hits,setHits]=useState<SearchHit[]>([]);const[dark,setDark]=useState(false);const[busy,setBusy]=useState(false);const[stats,setStats]=useState<Stats|null>(null);const[category,setCategory]=useState('');
useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);useEffect(()=>{api.stats().then(setStats).catch(()=>{})},[]);
async function loadLibrary(cat=''){setBusy(true);try{setCategory(cat);setWorks(await api.works('',cat));setView('library')}finally{setBusy(false)}}
async function openWork(w:Work,section?:number){setBusy(true);try{setSelected(w);const sec=await api.sections(w.id);setSections(sec);const first=section??sec[0]?.level1;setCurrentSection(first);setSegments(await api.segments(w.id,first));setView('reader')}finally{setBusy(false)}}
async function changeSection(n:number){if(!selected)return;setBusy(true);try{setCurrentSection(n);setSegments(await api.segments(selected.id,n));window.scrollTo({top:0,behavior:'smooth'})}finally{setBusy(false)}}
async function runSearch(e?:React.FormEvent){e?.preventDefault();if(q.trim().length<2)return;setBusy(true);try{setHits(await api.search(q.trim()));setView('search')}finally{setBusy(false)}}
const groups=useMemo(()=>{const m=new Map<string,Work[]>();works.forEach(w=>{const k=w.subcategory||categoryHe(w.category);m.set(k,[...(m.get(k)||[]),w])});return [...m.entries()]},[works]);const currentIndex=sections.findIndex(s=>s.level1===currentSection);const prev=sections[currentIndex-1]?.level1;const next=sections[currentIndex+1]?.level1;
return <div className="app"><header><button className="brand" onClick={()=>setView('home')}><span className="mark">א</span><span><b>אוצר ישראל</b><small>ארון הספרים היהודי</small></span></button><nav><button onClick={()=>setView('home')}>בית</button><button onClick={()=>loadLibrary()}>ספרייה</button><button onClick={()=>{setQ('');setHits([]);setView('search')}}>חיפוש</button></nav><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button></header>
<main>{view==='home'&&<><section className="hero"><div className="kicker"><Sparkles size={16}/> כל ארון הספרים היהודי במקום אחד</div><h1>לגלות. ללמוד. להתפלל.<br/><span>אוצר ישראל.</span></h1><p>מאגר יהודי פתוח שמחבר תנ״ך, חז״ל, הלכה, תפילה, מחשבה ופרשנות למרחב לימוד אחד.</p><form className="searchbox" onSubmit={runSearch}><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="חפש פסוק, ביטוי, ספר או נושא..."/><button>חיפוש</button></form>{stats&&<div className="stats"><div><BarChart3/><b>{stats.works.toLocaleString()}</b><span>ספרים</span></div><div><ScrollText/><b>{stats.segments.toLocaleString()}</b><span>קטעי טקסט</span></div><div><Library/><b>{stats.categories.length}</b><span>קטגוריות</span></div></div>}</section><section className="section"><div className="sectionHead"><div><span>הספרייה</span><h2>פתח את ארון הספרים</h2></div><button className="link" onClick={()=>loadLibrary()}>לכל הספרים <ChevronLeft/></button></div><div className="grid">{seeds.map(([key,t,d])=><button className="category" key={key} onClick={()=>loadLibrary(key)}><BookOpen/><b>{t}</b><span>{d}</span>{stats&&<small>{stats.categories.find(c=>c.name===key)?.count||0} ספרים</small>}</button>)}</div></section><section className="features"><div><ScrollText/><b>מקור ורישיון לכל טקסט</b><span>כל מהדורה נשמרת עם מקור שימוש ברור.</span></div><div><Search/><b>חיפוש עברי מנורמל</b><span>חיפוש גם בטקסט מנוקד ובכתיב משתנה.</span></div><div><Library/><b>מבנה שמוכן לגדול</b><span>מתוכנן מראש לעשרות אלפי יצירות.</span></div></section></>}
{view==='library'&&<section className="page"><div className="sectionHead"><div><span>{category?categoryHe(category):'כל המאגר'}</span><h1>ספריית אוצר ישראל</h1><p>{works.length.toLocaleString()} ספרים זמינים כעת</p></div>{category&&<button className="link" onClick={()=>loadLibrary()}>כל הקטגוריות</button>}</div>{busy?<div className="empty">טוען…</div>:works.length===0?<div className="empty"><BookOpen/><b>עדיין אין ספרים בקטגוריה הזו</b></div>:<div className="libraryGroups">{groups.map(([g,list])=><section key={g}><h2>{g}</h2><div className="bookList">{list.map(w=><button key={w.id} onClick={()=>openWork(w)}><div><b>{w.title_he}</b><span>{categoryHe(w.category)}{w.author?` · ${w.author}`:''}</span></div><ChevronLeft/></button>)}</div></section>)}</div>}</section>}
{view==='reader'&&selected&&<section className="reader"><aside><span>{categoryHe(selected.category)}</span><h2>{selected.title_he}</h2><button onClick={()=>loadLibrary(selected.category)}>חזרה לספרייה</button>{sections.length>0&&<div className="sectionNav"><b>פרקים / חלקים</b><div>{sections.map(s=><button className={s.level1===currentSection?'active':''} key={s.level1} onClick={()=>changeSection(s.level1)}>{s.level1}</button>)}</div></div>}</aside><article><div className="readerTop"><div><small>{selected.subcategory||categoryHe(selected.category)}</small><h1>{selected.title_he}</h1>{currentSection&&<span>חלק {currentSection}</span>}</div><div><button className="icon"><Heart/></button><button className="icon"><History/></button></div></div>{busy?<div className="empty">טוען…</div>:segments.map(s=><p key={s.id}><sup>{s.level2||s.level3||s.ref.split(' ').slice(-1)}</sup>{s.text}</p>)}<div className="pager"><button disabled={!prev} onClick={()=>prev&&changeSection(prev)}><ChevronRight/> הקודם</button><button disabled={!next} onClick={()=>next&&changeSection(next)}>הבא <ChevronLeft/></button></div></article></section>}
{view==='search'&&<section className="page"><h1>חיפוש באוצר ישראל</h1><form className="searchbox compact" onSubmit={runSearch}><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="מה תרצה למצוא?"/><button>חיפוש</button></form>{busy?<div className="empty">מחפש…</div>:hits.length?<div className="results">{hits.map((h,i)=><button key={i} onClick={async()=>{const w=(await api.works()).find(x=>x.id===h.work_id);if(w)openWork(w)}}><b>{h.work_title}</b><small>{h.ref}</small><p>{h.text}</p></button>)}</div>:q?<div className="empty">לא נמצאו תוצאות.</div>:<div className="empty"><Search/><b>חיפוש בכל ארון הספרים</b><span>כתוב לפחות שתי אותיות כדי להתחיל.</span></div>}</section>}</main><footer>אוצר ישראל · מאגר יהודי חי</footer></div>}
