import {useEffect,useMemo,useState} from 'react'
import {BarChart3,BookOpen,ChevronLeft,ChevronRight,Library,Moon,Search,ScrollText,Sparkles,Sun} from 'lucide-react'
import {api,KetuvimBook,MishnahSeder,MishnahTractate,MishnahUnit,NeviimBook,SearchHit,Stats,TalmudSectionInfo,TalmudSegment,TalmudTradition,TalmudTractate,TorahBook,TorahParasha,TorahVerse} from './services/api'
import './home.css'

type View='home'|'search'|'tanakh'|'torah'|'torahBook'|'parasha'|'torahBookView'|'neviim'|'neviimBook'|'neviimChapter'|'neviimBookView'|'ketuvim'|'ketuvimBook'|'ketuvimChapter'|'ketuvimBookView'|'mishnah'|'mishnahSeder'|'mishnahTractate'|'mishnahChapter'|'mishnahTractateView'|'talmud'|'talmudTradition'|'talmudTractate'|'talmudSection'|'talmudTractateView'

const homeCategories=[
  ['tanakh','תנ״ך','תורה, נביאים וכתובים'],['mishnah','משנה','שישה סדרי משנה'],['talmud','תלמוד','בבלי וירושלמי'],['halakha','הלכה','רמב״ם, טור ושולחן ערוך'],['prayer','תפילה','סידורים, מחזורים ופיוטים'],['midrash','מדרש','מדרשי חז״ל'],['musar','מוסר','ספרי מוסר ומחשבה'],['chasidut','חסידות','ספרי חסידות'],
]

function heNumber(n:number){
  if(n<=0)return String(n)
  const parts:[number,string][]=[[400,'ת'],[300,'ש'],[200,'ר'],[100,'ק'],[90,'צ'],[80,'פ'],[70,'ע'],[60,'ס'],[50,'נ'],[40,'מ'],[30,'ל'],[20,'כ'],[10,'י'],[9,'ט'],[8,'ח'],[7,'ז'],[6,'ו'],[5,'ה'],[4,'ד'],[3,'ג'],[2,'ב'],[1,'א']]
  let value=n;let out=''
  while(value>=400){out+='ת';value-=400}
  if(value===15){out+='טו';value=0}else if(value===16){out+='טז';value=0}else{for(const [v,l] of parts){if(v>=400)continue;while(value>=v){out+=l;value-=v}}}
  if(out.length===1)return `${out}׳`
  return `${out.slice(0,-1)}״${out.slice(-1)}`
}

function traditionTitle(t:TalmudTradition){return t==='bavli'?'תלמוד בבלי':'תלמוד ירושלמי'}

export default function App(){
  const[view,setView]=useState<View>('home');const[dark,setDark]=useState(false);const[busy,setBusy]=useState(false);const[stats,setStats]=useState<Stats|null>(null);const[q,setQ]=useState('');const[hits,setHits]=useState<SearchHit[]>([])
  const[torahBooks,setTorahBooks]=useState<TorahBook[]>([]);const[selectedTorah,setSelectedTorah]=useState<TorahBook|null>(null);const[parashot,setParashot]=useState<TorahParasha[]>([]);const[selectedParasha,setSelectedParasha]=useState<TorahParasha|null>(null);const[currentChapter,setCurrentChapter]=useState<number|null>(null);const[verses,setVerses]=useState<TorahVerse[]>([]);const[bookVerses,setBookVerses]=useState<TorahVerse[]>([])
  const[neviimBooks,setNeviimBooks]=useState<NeviimBook[]>([]);const[selectedNeviim,setSelectedNeviim]=useState<NeviimBook|null>(null);const[neviimChapter,setNeviimChapter]=useState<number|null>(null);const[neviimVerses,setNeviimVerses]=useState<TorahVerse[]>([]);const[neviimBookVerses,setNeviimBookVerses]=useState<TorahVerse[]>([])
  const[ketuvimBooks,setKetuvimBooks]=useState<KetuvimBook[]>([]);const[selectedKetuvim,setSelectedKetuvim]=useState<KetuvimBook|null>(null);const[ketuvimChapter,setKetuvimChapter]=useState<number|null>(null);const[ketuvimVerses,setKetuvimVerses]=useState<TorahVerse[]>([]);const[ketuvimBookVerses,setKetuvimBookVerses]=useState<TorahVerse[]>([])
  const[mishnahSedarim,setMishnahSedarim]=useState<MishnahSeder[]>([]);const[selectedSeder,setSelectedSeder]=useState<MishnahSeder|null>(null);const[mishnahTractates,setMishnahTractates]=useState<MishnahTractate[]>([]);const[selectedTractate,setSelectedTractate]=useState<MishnahTractate|null>(null);const[mishnahChapter,setMishnahChapter]=useState<number|null>(null);const[mishnahUnits,setMishnahUnits]=useState<MishnahUnit[]>([]);const[mishnahFull,setMishnahFull]=useState<MishnahUnit[]>([])
  const[talmudTradition,setTalmudTradition]=useState<TalmudTradition>('bavli');const[talmudTractates,setTalmudTractates]=useState<TalmudTractate[]>([]);const[selectedTalmud,setSelectedTalmud]=useState<TalmudTractate|null>(null);const[talmudSections,setTalmudSections]=useState<TalmudSectionInfo[]>([]);const[currentTalmudSection,setCurrentTalmudSection]=useState<number|null>(null);const[talmudSegments,setTalmudSegments]=useState<TalmudSegment[]>([]);const[talmudFull,setTalmudFull]=useState<TalmudSegment[]>([])

  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);useEffect(()=>{api.stats().then(setStats).catch(()=>{})},[])
  function openLibrary(){setView('home');setTimeout(()=>document.getElementById('library')?.scrollIntoView({behavior:'smooth'}),0)}
  async function runSearch(e?:React.FormEvent){e?.preventDefault();if(q.trim().length<2)return;setBusy(true);try{setHits(await api.search(q.trim()));setView('search')}finally{setBusy(false)}}

  async function openTorah(){setBusy(true);try{setTorahBooks(await api.torahBooks());setView('torah')}finally{setBusy(false)}}
  async function openTorahBook(book:TorahBook){setBusy(true);try{setSelectedTorah(book);setSelectedParasha(null);setParashot(await api.torahParashot(book.slug));setView('torahBook')}finally{setBusy(false)}}
  async function openParasha(p:TorahParasha){setBusy(true);try{setSelectedParasha(p);setCurrentChapter(p.start_chapter);setVerses(await api.torahParashaChapter(p.id,p.start_chapter));setView('parasha');window.scrollTo({top:0})}finally{setBusy(false)}}
  async function changeParashaChapter(ch:number){if(!selectedParasha)return;setBusy(true);try{setCurrentChapter(ch);setVerses(await api.torahParashaChapter(selectedParasha.id,ch));window.scrollTo({top:0,behavior:'smooth'})}finally{setBusy(false)}}
  async function openTorahBookView(){if(!selectedTorah)return;setBusy(true);try{setBookVerses(await api.torahBookView(selectedTorah.slug));setView('torahBookView');window.scrollTo({top:0})}finally{setBusy(false)}}

  async function openNeviim(){setBusy(true);try{setNeviimBooks(await api.neviimBooks());setView('neviim')}finally{setBusy(false)}}
  function openNeviimBook(book:NeviimBook){setSelectedNeviim(book);setNeviimChapter(null);setNeviimVerses([]);setView('neviimBook')}
  async function openNeviimChapter(ch:number){if(!selectedNeviim)return;setBusy(true);try{setNeviimChapter(ch);setNeviimVerses(await api.neviimChapter(selectedNeviim.slug,ch));setView('neviimChapter');window.scrollTo({top:0})}finally{setBusy(false)}}
  async function openNeviimBookView(){if(!selectedNeviim)return;setBusy(true);try{setNeviimBookVerses(await api.neviimBookView(selectedNeviim.slug));setView('neviimBookView');window.scrollTo({top:0})}finally{setBusy(false)}}

  async function openKetuvim(){setBusy(true);try{setKetuvimBooks(await api.ketuvimBooks());setView('ketuvim')}finally{setBusy(false)}}
  function openKetuvimBook(book:KetuvimBook){setSelectedKetuvim(book);setKetuvimChapter(null);setKetuvimVerses([]);setView('ketuvimBook')}
  async function openKetuvimChapter(ch:number){if(!selectedKetuvim)return;setBusy(true);try{setKetuvimChapter(ch);setKetuvimVerses(await api.ketuvimChapter(selectedKetuvim.slug,ch));setView('ketuvimChapter');window.scrollTo({top:0})}finally{setBusy(false)}}
  async function openKetuvimBookView(){if(!selectedKetuvim)return;setBusy(true);try{setKetuvimBookVerses(await api.ketuvimBookView(selectedKetuvim.slug));setView('ketuvimBookView');window.scrollTo({top:0})}finally{setBusy(false)}}

  async function openMishnah(){setBusy(true);try{setMishnahSedarim(await api.mishnahSedarim());setView('mishnah')}finally{setBusy(false)}}
  async function openMishnahSeder(s:MishnahSeder){setBusy(true);try{setSelectedSeder(s);setMishnahTractates(await api.mishnahTractates(s.slug));setView('mishnahSeder')}finally{setBusy(false)}}
  function openMishnahTractate(t:MishnahTractate){setSelectedTractate(t);setMishnahChapter(null);setMishnahUnits([]);setView('mishnahTractate')}
  async function openMishnahChapter(ch:number){if(!selectedTractate)return;setBusy(true);try{setMishnahChapter(ch);setMishnahUnits(await api.mishnahChapter(selectedTractate.slug,ch));setView('mishnahChapter');window.scrollTo({top:0})}finally{setBusy(false)}}
  async function openMishnahTractateView(){if(!selectedTractate)return;setBusy(true);try{setMishnahFull(await api.mishnahTractateView(selectedTractate.slug));setView('mishnahTractateView');window.scrollTo({top:0})}finally{setBusy(false)}}

  async function openTalmudTradition(tradition:TalmudTradition){setBusy(true);try{setTalmudTradition(tradition);setSelectedTalmud(null);setTalmudTractates(await api.talmudTractates(tradition));setView('talmudTradition')}finally{setBusy(false)}}
  async function openTalmudTractate(t:TalmudTractate){setBusy(true);try{setSelectedTalmud(t);setCurrentTalmudSection(null);setTalmudSegments([]);setTalmudSections(await api.talmudSections(talmudTradition,t.slug));setView('talmudTractate')}finally{setBusy(false)}}
  async function openTalmudSection(section:number){if(!selectedTalmud)return;setBusy(true);try{setCurrentTalmudSection(section);setTalmudSegments(await api.talmudSection(talmudTradition,selectedTalmud.slug,section));setView('talmudSection');window.scrollTo({top:0})}finally{setBusy(false)}}
  async function openTalmudTractateView(){if(!selectedTalmud)return;setBusy(true);try{setTalmudFull(await api.talmudBookView(talmudTradition,selectedTalmud.slug));setView('talmudTractateView');window.scrollTo({top:0})}finally{setBusy(false)}}

  const torahGroups=useMemo(()=>groupByChapter(bookVerses),[bookVerses]);const neviimGroups=useMemo(()=>groupByChapter(neviimBookVerses),[neviimBookVerses]);const ketuvimGroups=useMemo(()=>groupByChapter(ketuvimBookVerses),[ketuvimBookVerses]);const mishnahGroups=useMemo(()=>groupMishnahByChapter(mishnahFull),[mishnahFull]);const talmudSederGroups=useMemo(()=>groupTalmudBySeder(talmudTractates),[talmudTractates]);const talmudFullGroups=useMemo(()=>groupTalmudBySection(talmudFull),[talmudFull])
  const parashaIndex=selectedParasha&&currentChapter?selectedParasha.chapters.indexOf(currentChapter):-1;const prevParashaChapter=selectedParasha&&parashaIndex>0?selectedParasha.chapters[parashaIndex-1]:null;const nextParashaChapter=selectedParasha&&parashaIndex>=0?selectedParasha.chapters[parashaIndex+1]||null:null
  const currentTalmudIndex=currentTalmudSection?talmudSections.findIndex(s=>s.index===currentTalmudSection):-1;const prevTalmudSection=currentTalmudIndex>0?talmudSections[currentTalmudIndex-1]?.index:null;const nextTalmudSection=currentTalmudIndex>=0?talmudSections[currentTalmudIndex+1]?.index:null;const currentTalmudLabel=currentTalmudSection?talmudSections.find(s=>s.index===currentTalmudSection)?.label:''

  return <div className="app"><header><button className="brand" onClick={()=>setView('home')}><span className="mark">א</span><span><b>אוצר ישראל</b><small>ארון הספרים היהודי</small></span></button><nav><button onClick={()=>setView('home')}>בית</button><button onClick={openLibrary}>ספרייה</button><button onClick={()=>{setQ('');setHits([]);setView('search')}}>חיפוש</button></nav><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button></header><main>

  {view==='home'&&<><section className="hero"><div className="kicker"><Sparkles size={16}/> כל ארון הספרים היהודי במקום אחד</div><h1>לגלות. ללמוד. להתפלל.<br/><span>אוצר ישראל.</span></h1><p>מאגר יהודי פתוח שמחבר תנ״ך, חז״ל, הלכה, תפילה, מחשבה ופרשנות למרחב לימוד אחד.</p><form className="searchbox" onSubmit={runSearch}><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="חפש פסוק, ביטוי, ספר או נושא..."/><button>חיפוש</button></form>{stats&&<div className="stats"><div><BarChart3/><b>{stats.works.toLocaleString()}</b><span>ספרים</span></div><div><ScrollText/><b>{stats.segments.toLocaleString()}</b><span>קטעי טקסט</span></div><div><Library/><b>{stats.categories.length}</b><span>קטגוריות</span></div></div>}</section><section className="section" id="library"><div className="sectionHead"><div><span>הספרייה</span><h2>פתח את ארון הספרים</h2></div></div><div className="grid">{homeCategories.map(([key,title,desc])=>{const active=key==='tanakh'||key==='mishnah'||key==='talmud';return <button key={key} className="category" onClick={()=>key==='tanakh'?setView('tanakh'):key==='mishnah'?openMishnah():key==='talmud'?setView('talmud'):undefined} disabled={!active}><BookOpen/><b>{title}</b><span>{desc}</span><small>{active?'פתוח לקריאה':'בהמשך'}</small></button>})}</div></section><section className="features"><div><ScrollText/><b>מקור ורישיון לכל טקסט</b><span>כל מהדורה נשמרת עם מקור שימוש ברור.</span></div><div><Search/><b>חיפוש עברי מנורמל</b><span>חיפוש גם בטקסט מנוקד ובכתיב משתנה.</span></div><div><Library/><b>מבנה שמוכן לגדול</b><span>מתוכנן מראש לארון ספרים יהודי רחב.</span></div></section></>}

  {view==='search'&&<section className="page"><div className="pageTitle"><span>חיפוש</span><h1>חיפוש באוצר ישראל</h1></div><form className="searchbox compact" onSubmit={runSearch}><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="מה תרצה למצוא?"/><button>חיפוש</button></form>{busy?<Loading/>:hits.length?<div className="results">{hits.map((h,i)=><div className="resultCard" key={i}><b>{h.work_title}</b><small>{h.ref}</small><p>{h.text}</p></div>)}</div>:<div className="empty">לא נמצאו תוצאות.</div>}</section>}

  {view==='tanakh'&&<section className="page"><Crumbs items={[['בית',()=>setView('home')]]} current="תנ״ך"/><div className="pageTitle"><span>תנ״ך</span><h1>תורה · נביאים · כתובים</h1></div><div className="grid threeGrid"><button className="category primaryCard" onClick={openTorah}><ScrollText/><b>תורה</b><span>חמשת חומשי תורה, פרשות, פרקים ופסוקים</span></button><button className="category primaryCard" onClick={openNeviim}><BookOpen/><b>נביאים</b><span>ספרי הנביאים לפי הסדר, פרקים ופסוקים</span></button><button className="category primaryCard" onClick={openKetuvim}><Library/><b>כתובים</b><span>ספרי הכתובים לפי הסדר, פרקים ופסוקים</span></button></div></section>}

  {view==='torah'&&<section className="page"><Crumbs items={[['תנ״ך',()=>setView('tanakh')]]} current="תורה"/><div className="pageTitle"><span>תורה</span><h1>חמשת חומשי תורה</h1></div>{busy?<Loading/>:<div className="grid fiveGrid">{torahBooks.map(b=><BookCard key={b.id} book={b} onClick={()=>openTorahBook(b)}/>)}</div>}</section>}
  {view==='torahBook'&&selectedTorah&&<section className="page"><Crumbs items={[['תורה',openTorah]]} current={selectedTorah.title_he}/><div className="bookHero"><div><span>חומש</span><h1>{selectedTorah.title_he}</h1><p>{selectedTorah.chapter_count} פרקים · טקסט עברי מנוקד</p></div><button className="bookViewButton" onClick={openTorahBookView}><BookOpen/> תצוגת ספר מלאה</button></div><div className="sectionHead"><div><span>לפי פרשות</span><h2>פרשות ספר {selectedTorah.title_he}</h2></div></div><div className="parashaGrid">{parashot.map(p=><button className="parashaCard" key={p.id} onClick={()=>openParasha(p)}><small>פרשה {p.order}</small><b>פרשת {p.title_he}</b><span>{p.chapters.length===1?`פרק ${heNumber(p.start_chapter)}`:`פרקים ${heNumber(p.start_chapter)}–${heNumber(p.end_chapter)}`}</span><ChevronLeft/></button>)}</div><Source book={selectedTorah}/></section>}
  {view==='parasha'&&selectedTorah&&selectedParasha&&<section className="readerShell"><aside className="readerSidebar"><button className="backLink" onClick={()=>setView('torahBook')}><ChevronRight/> חזרה לספר {selectedTorah.title_he}</button><span>ספר {selectedTorah.title_he}</span><h2>פרשת {selectedParasha.title_he}</h2><b>פרקים בפרשה</b><div className="chapterButtons">{selectedParasha.chapters.map(ch=><button key={ch} className={ch===currentChapter?'active':''} onClick={()=>changeParashaChapter(ch)}>פרק {heNumber(ch)}</button>)}</div></aside><article className="torahReader"><ReaderHeading sub={`ספר ${selectedTorah.title_he} · פרשת ${selectedParasha.title_he}`} title={`פרק ${currentChapter?heNumber(currentChapter):''}`}/>{busy?<Loading/>:<Verses verses={verses}/>}<div className="pager"><button disabled={!prevParashaChapter} onClick={()=>prevParashaChapter&&changeParashaChapter(prevParashaChapter)}><ChevronRight/> פרק קודם</button><button disabled={!nextParashaChapter} onClick={()=>nextParashaChapter&&changeParashaChapter(nextParashaChapter)}>פרק הבא <ChevronLeft/></button></div></article></section>}
  {view==='torahBookView'&&selectedTorah&&<FullBook title={selectedTorah.title_he} groups={torahGroups} back={()=>setView('torahBook')}/>} 

  {view==='neviim'&&<section className="page"><Crumbs items={[['תנ״ך',()=>setView('tanakh')]]} current="נביאים"/><div className="pageTitle"><span>נביאים</span><h1>ספרי הנביאים</h1><p>לפי סדר התנ״ך. בחר ספר לקריאה לפי פרקים או בתצוגת ספר מלאה.</p></div>{busy?<Loading/>:<div className="grid prophetsGrid">{neviimBooks.map(b=><BookCard key={b.id} book={b} onClick={()=>openNeviimBook(b)}/>)}</div>}</section>}
  {view==='neviimBook'&&selectedNeviim&&<TanakhBookPage section="נביאים" book={selectedNeviim} back={openNeviim} openChapter={openNeviimChapter} openFull={openNeviimBookView}/>} 
  {view==='neviimChapter'&&selectedNeviim&&neviimChapter&&<TanakhChapterPage section="נביאים" book={selectedNeviim} chapter={neviimChapter} verses={neviimVerses} busy={busy} back={()=>setView('neviimBook')} openChapter={openNeviimChapter}/>} 
  {view==='neviimBookView'&&selectedNeviim&&<FullBook title={selectedNeviim.title_he} groups={neviimGroups} back={()=>setView('neviimBook')}/>} 

  {view==='ketuvim'&&<section className="page"><Crumbs items={[['תנ״ך',()=>setView('tanakh')]]} current="כתובים"/><div className="pageTitle"><span>כתובים</span><h1>ספרי הכתובים</h1><p>לפי סדר התנ״ך. בחר ספר לקריאה לפי פרקים או בתצוגת ספר מלאה.</p></div>{busy?<Loading/>:<div className="grid prophetsGrid">{ketuvimBooks.map(b=><BookCard key={b.id} book={b} onClick={()=>openKetuvimBook(b)}/>)}</div>}</section>}
  {view==='ketuvimBook'&&selectedKetuvim&&<TanakhBookPage section="כתובים" book={selectedKetuvim} back={openKetuvim} openChapter={openKetuvimChapter} openFull={openKetuvimBookView}/>} 
  {view==='ketuvimChapter'&&selectedKetuvim&&ketuvimChapter&&<TanakhChapterPage section="כתובים" book={selectedKetuvim} chapter={ketuvimChapter} verses={ketuvimVerses} busy={busy} back={()=>setView('ketuvimBook')} openChapter={openKetuvimChapter}/>} 
  {view==='ketuvimBookView'&&selectedKetuvim&&<FullBook title={selectedKetuvim.title_he} groups={ketuvimGroups} back={()=>setView('ketuvimBook')}/>} 

  {view==='mishnah'&&<section className="page"><Crumbs items={[['בית',()=>setView('home')]]} current="משנה"/><div className="pageTitle"><span>משנה</span><h1>שישה סדרי משנה</h1><p>זרעים · מועד · נשים · נזיקין · קדשים · טהרות</p></div>{busy?<Loading/>:<div className="grid threeGrid">{mishnahSedarim.map(s=><button className="category primaryCard" key={s.id} onClick={()=>openMishnahSeder(s)}><ScrollText/><b>סדר {s.title_he}</b><span>{s.tractate_count} מסכתות</span></button>)}</div>}</section>}
  {view==='mishnahSeder'&&selectedSeder&&<section className="page"><Crumbs items={[['משנה',openMishnah]]} current={`סדר ${selectedSeder.title_he}`}/><div className="pageTitle"><span>משנה</span><h1>סדר {selectedSeder.title_he}</h1><p>המסכתות לפי סדר המשנה.</p></div>{busy?<Loading/>:<div className="grid prophetsGrid">{mishnahTractates.map(t=><button className="category bookCard" key={t.id} onClick={()=>openMishnahTractate(t)}><ScrollText/><b>{t.title_he}</b><span>{t.chapter_count} פרקים</span><small>{t.license}</small></button>)}</div>}</section>}
  {view==='mishnahTractate'&&selectedSeder&&selectedTractate&&<section className="page"><Crumbs items={[[`סדר ${selectedSeder.title_he}`,()=>openMishnahSeder(selectedSeder)]]} current={selectedTractate.title_he}/><div className="bookHero"><div><span>משנה · סדר {selectedSeder.title_he}</span><h1>מסכת {selectedTractate.title_he}</h1><p>{selectedTractate.chapter_count} פרקים</p></div><button className="bookViewButton" onClick={openMishnahTractateView}><BookOpen/> תצוגת מסכת מלאה</button></div><div className="sectionHead"><div><span>לפי פרקים</span><h2>פרקי מסכת {selectedTractate.title_he}</h2></div></div><div className="chapterIndex">{Array.from({length:selectedTractate.chapter_count},(_,i)=>i+1).map(ch=><button key={ch} onClick={()=>openMishnahChapter(ch)}>פרק {heNumber(ch)}</button>)}</div><div className="sourceNote">מקור הטקסט: {selectedTractate.source_name} · רישיון: {selectedTractate.license}</div></section>}
  {view==='mishnahChapter'&&selectedSeder&&selectedTractate&&mishnahChapter&&<section className="readerShell"><aside className="readerSidebar"><button className="backLink" onClick={()=>setView('mishnahTractate')}><ChevronRight/> חזרה למסכת {selectedTractate.title_he}</button><span>סדר {selectedSeder.title_he}</span><h2>מסכת {selectedTractate.title_he}</h2><b>פרקים במסכת</b><div className="chapterButtons">{Array.from({length:selectedTractate.chapter_count},(_,i)=>i+1).map(ch=><button key={ch} className={ch===mishnahChapter?'active':''} onClick={()=>openMishnahChapter(ch)}>פרק {heNumber(ch)}</button>)}</div></aside><article className="torahReader"><ReaderHeading sub={`מסכת ${selectedTractate.title_he}`} title={`פרק ${heNumber(mishnahChapter)}`}/>{busy?<Loading/>:<Mishnayot units={mishnahUnits}/>}<div className="pager"><button disabled={mishnahChapter<=1} onClick={()=>openMishnahChapter(mishnahChapter-1)}><ChevronRight/> פרק קודם</button><button disabled={mishnahChapter>=selectedTractate.chapter_count} onClick={()=>openMishnahChapter(mishnahChapter+1)}>פרק הבא <ChevronLeft/></button></div></article></section>}
  {view==='mishnahTractateView'&&selectedTractate&&<section className="bookReaderPage"><div className="bookReaderHeader"><button className="backLink" onClick={()=>setView('mishnahTractate')}><ChevronRight/> חזרה למסכת</button><span>תצוגת מסכת</span><h1>מסכת {selectedTractate.title_he}</h1><p>מהמשנה הראשונה ועד האחרונה, לפי פרקים.</p></div><article className="fullBook">{mishnahGroups.map(([chapter,rows])=><section className="bookChapter" key={chapter}><h2>פרק {heNumber(chapter)}</h2><Mishnayot units={rows}/></section>)}</article></section>}

  {view==='talmud'&&<section className="page"><Crumbs items={[['בית',()=>setView('home')]]} current="תלמוד"/><div className="pageTitle"><span>תלמוד</span><h1>תלמוד בבלי · תלמוד ירושלמי</h1><p>שני מאגרים נפרדים. בחר את מסורת התלמוד שברצונך ללמוד.</p></div><div className="grid threeGrid"><button className="category primaryCard" onClick={()=>openTalmudTradition('bavli')}><ScrollText/><b>תלמוד בבלי</b><span>מסכתות הש״ס הבבלי לפי סדרים ודפים</span></button><button className="category primaryCard" onClick={()=>openTalmudTradition('yerushalmi')}><BookOpen/><b>תלמוד ירושלמי</b><span>מסכתות התלמוד הירושלמי במאגר נפרד</span></button></div></section>}
  {view==='talmudTradition'&&<section className="page"><Crumbs items={[['תלמוד',()=>setView('talmud')]]} current={traditionTitle(talmudTradition)}/><div className="pageTitle"><span>תלמוד</span><h1>{traditionTitle(talmudTradition)}</h1><p>{talmudTradition==='bavli'?'מסכתות הש״ס הבבלי לפי סדרים.':'מסכתות התלמוד הירושלמי לפי סדרים.'}</p></div>{busy?<Loading/>:talmudSederGroups.length?talmudSederGroups.map(([seder,tractates])=><section key={seder||'other'}><div className="sectionHead"><div><span>סדר</span><h2>{seder||'מסכתות נוספות'}</h2></div></div><div className="grid prophetsGrid">{tractates.map(t=><button className="category bookCard" key={t.id} onClick={()=>openTalmudTractate(t)}><ScrollText/><b>{t.title_he}</b><span>{talmudTradition==='bavli'?`${t.section_count} עמודים`:`${t.section_count} פרקים`}</span><small>{t.license}</small></button>)}</div></section>):<div className="empty">עדיין אין מסכתות עם רישיון מאומת להצגה.</div>}</section>}
  {view==='talmudTractate'&&selectedTalmud&&<section className="page"><Crumbs items={[[traditionTitle(talmudTradition),()=>openTalmudTradition(talmudTradition)]]} current={selectedTalmud.title_he}/><div className="bookHero"><div><span>{traditionTitle(talmudTradition)}{selectedTalmud.seder_name?` · סדר ${selectedTalmud.seder_name}`:''}</span><h1>מסכת {selectedTalmud.title_he}</h1><p>{talmudTradition==='bavli'?`${talmudSections.length} דפים/עמודים זמינים`:`${talmudSections.length} פרקים זמינים`}</p></div><button className="bookViewButton" onClick={openTalmudTractateView}><BookOpen/> תצוגת מסכת מלאה</button></div><div className="sectionHead"><div><span>{talmudTradition==='bavli'?'לפי דפים':'לפי פרקים'}</span><h2>מסכת {selectedTalmud.title_he}</h2></div></div><div className="chapterIndex">{talmudSections.map(s=><button key={s.index} onClick={()=>openTalmudSection(s.index)}>{s.label}</button>)}</div><div className="sourceNote">מקור הטקסט: {selectedTalmud.source_name} · רישיון: {selectedTalmud.license}</div></section>}
  {view==='talmudSection'&&selectedTalmud&&currentTalmudSection&&<section className="readerShell"><aside className="readerSidebar"><button className="backLink" onClick={()=>setView('talmudTractate')}><ChevronRight/> חזרה למסכת {selectedTalmud.title_he}</button><span>{traditionTitle(talmudTradition)}</span><h2>מסכת {selectedTalmud.title_he}</h2><b>{talmudTradition==='bavli'?'דפים במסכת':'פרקים במסכת'}</b><div className="chapterButtons">{talmudSections.map(s=><button key={s.index} className={s.index===currentTalmudSection?'active':''} onClick={()=>openTalmudSection(s.index)}>{s.label}</button>)}</div></aside><article className="torahReader"><ReaderHeading sub={`${traditionTitle(talmudTradition)} · מסכת ${selectedTalmud.title_he}`} title={currentTalmudLabel||`חלק ${currentTalmudSection}`}/>{busy?<Loading/>:<TalmudText segments={talmudSegments}/>}<div className="pager"><button disabled={!prevTalmudSection} onClick={()=>prevTalmudSection&&openTalmudSection(prevTalmudSection)}><ChevronRight/> הקודם</button><button disabled={!nextTalmudSection} onClick={()=>nextTalmudSection&&openTalmudSection(nextTalmudSection)}>הבא <ChevronLeft/></button></div></article></section>}
  {view==='talmudTractateView'&&selectedTalmud&&<section className="bookReaderPage"><div className="bookReaderHeader"><button className="backLink" onClick={()=>setView('talmudTractate')}><ChevronRight/> חזרה למסכת</button><span>תצוגת מסכת · {traditionTitle(talmudTradition)}</span><h1>מסכת {selectedTalmud.title_he}</h1><p>הטקסט המלא ברצף, בחלוקה המקורית של המאגר.</p></div><article className="fullBook">{talmudFullGroups.map(([section,rows])=><section className="bookChapter" key={section}><h2>{talmudSections.find(s=>s.index===section)?.label||`חלק ${section}`}</h2><TalmudText segments={rows}/></section>)}</article></section>}

  </main><footer>אוצר ישראל · ארון הספרים היהודי</footer></div>
}

function groupByChapter(rows:TorahVerse[]){const m=new Map<number,TorahVerse[]>();rows.forEach(v=>m.set(v.chapter,[...(m.get(v.chapter)||[]),v]));return [...m.entries()]}
function groupMishnahByChapter(rows:MishnahUnit[]){const m=new Map<number,MishnahUnit[]>();rows.forEach(v=>m.set(v.chapter,[...(m.get(v.chapter)||[]),v]));return [...m.entries()]}
function groupTalmudBySeder(rows:TalmudTractate[]){const m=new Map<string,TalmudTractate[]>();rows.forEach(v=>m.set(v.seder_name,[...(m.get(v.seder_name)||[]),v]));return [...m.entries()]}
function groupTalmudBySection(rows:TalmudSegment[]){const m=new Map<number,TalmudSegment[]>();rows.forEach(v=>m.set(v.section,[...(m.get(v.section)||[]),v]));return [...m.entries()]}
function Loading(){return <div className="empty">טוען…</div>}
function Verses({verses}:{verses:TorahVerse[]}){return <div className="verses">{verses.map(v=><p key={v.id}><sup>{heNumber(v.verse)}</sup>{v.text}</p>)}</div>}
function Mishnayot({units}:{units:MishnahUnit[]}){return <div className="verses">{units.map(m=><p key={m.id}><sup>{heNumber(m.mishnah)}</sup>{m.text}</p>)}</div>}
function TalmudText({segments}:{segments:TalmudSegment[]}){return <div className="verses">{segments.map(s=><p key={s.id}><sup>{heNumber(s.position)}</sup>{s.text}</p>)}</div>}
function ReaderHeading({sub,title}:{sub:string;title:string}){return <div className="readerHeading"><small>{sub}</small><h1>{title}</h1></div>}
function BookCard({book,onClick}:{book:TorahBook|NeviimBook|KetuvimBook;onClick:()=>void}){return <button className="category bookCard" onClick={onClick}><ScrollText/><b>{book.title_he}</b><span>{book.chapter_count} פרקים</span><small>{book.license}</small></button>}
function Source({book}:{book:TorahBook|NeviimBook|KetuvimBook}){return <div className="sourceNote">מקור הטקסט: {book.source_name} · רישיון: {book.license}</div>}
function Crumbs({items,current}:{items:[string,()=>void][];current:string}){return <div className="breadcrumbs">{items.map(([t,f])=><span key={t}><button onClick={f}>{t}</button><ChevronLeft/></span>)}<b>{current}</b></div>}
function FullBook({title,groups,back}:{title:string;groups:[number,TorahVerse[]][];back:()=>void}){return <section className="bookReaderPage"><div className="bookReaderHeader"><button className="backLink" onClick={back}><ChevronRight/> חזרה לספר</button><span>תצוגת ספר</span><h1>ספר {title}</h1><p>מהפסוק הראשון ועד הפסוק האחרון, ברצף מלא.</p></div><article className="fullBook">{groups.map(([chapter,rows])=><section className="bookChapter" key={chapter}><h2>פרק {heNumber(chapter)}</h2><Verses verses={rows}/></section>)}</article></section>}
function TanakhBookPage({section,book,back,openChapter,openFull}:{section:string;book:NeviimBook|KetuvimBook;back:()=>void;openChapter:(ch:number)=>void;openFull:()=>void}){return <section className="page"><Crumbs items={[[section,back]]} current={book.title_he}/><div className="bookHero"><div><span>{section}</span><h1>ספר {book.title_he}</h1><p>{book.chapter_count} פרקים · טקסט עברי מנוקד</p></div><button className="bookViewButton" onClick={openFull}><BookOpen/> תצוגת ספר מלאה</button></div><div className="sectionHead"><div><span>לפי פרקים</span><h2>פרקי ספר {book.title_he}</h2></div></div><div className="chapterIndex">{Array.from({length:book.chapter_count},(_,i)=>i+1).map(ch=><button key={ch} onClick={()=>openChapter(ch)}>פרק {heNumber(ch)}</button>)}</div><Source book={book}/></section>}
function TanakhChapterPage({section,book,chapter,verses,busy,back,openChapter}:{section:string;book:NeviimBook|KetuvimBook;chapter:number;verses:TorahVerse[];busy:boolean;back:()=>void;openChapter:(ch:number)=>void}){return <section className="readerShell"><aside className="readerSidebar"><button className="backLink" onClick={back}><ChevronRight/> חזרה לספר {book.title_he}</button><span>{section}</span><h2>ספר {book.title_he}</h2><b>פרקים בספר</b><div className="chapterButtons">{Array.from({length:book.chapter_count},(_,i)=>i+1).map(ch=><button key={ch} className={ch===chapter?'active':''} onClick={()=>openChapter(ch)}>פרק {heNumber(ch)}</button>)}</div></aside><article className="torahReader"><ReaderHeading sub={`ספר ${book.title_he}`} title={`פרק ${heNumber(chapter)}`}/>{busy?<Loading/>:<Verses verses={verses}/>}<div className="pager"><button disabled={chapter<=1} onClick={()=>openChapter(chapter-1)}><ChevronRight/> פרק קודם</button><button disabled={chapter>=book.chapter_count} onClick={()=>openChapter(chapter+1)}>פרק הבא <ChevronLeft/></button></div></article></section>}
